POST http://localhost:3000/seller/create
content-type: application/json

{
  "document": "86874893658901",
  "type_document": "PJ",
  "name": "Emainara Vendedora",
  "telephone": "+551985793654",
  "email": "may.vendedora@email.com",
  "address_code": "2548655",
  "address_street": "Rua Monte Santo de Minas",
  "address_number": 170,
  "address_complement": "",
  "address_city": null,
  "address_neighborhood": "Jardim Flor do Campo",
  "address_state": "São Paulo"
}

###
GET http://localhost:3000/seller/find-by-email
content-type: application/json

{
  "email": "lucas.vendedor@email.com"
}

###
GET http://localhost:3000/seller/find-by-document
content-type: application/json

{
  "document": "86874898901"
}